# Path to your dotfiles installation.
export DOTFILES=$HOME/.dotfiles

# Aliases, exports and functions
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/exports.zsh
if [ -f $DOTFILES/zsh/extra.zsh ]; then
  source $DOTFILES/zsh/extra.zsh
fi

# Plugins
source $DOTFILES/zsh/plugins/fzf.plugin.zsh
source $DOTFILES/zsh/plugins/git-trim/git-trim.plugin.zsh
source $DOTFILES/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $DOTFILES/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
source $DOTFILES/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# kitty: jumping words using option + arrows
# https://github.com/kovidgoyal/kitty/issues/838#issuecomment-770328902
bindkey "\e[1;3D" backward-word # ⌥←
bindkey "\e[1;3C" forward-word  # ⌥→

eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"
eval "$(atuin init zsh --disable-up-arrow)"

if [ -f /opt/homebrew/bin/mise ]; then
  eval "$(/opt/homebrew/bin/mise activate zsh)"
fi
