# Path to your dotfiles installation.
export DOTFILES=$HOME/.dotfiles

# Aliases, exports and functions
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/exports.zsh
if [ -f $DOTFILES/zsh/extra.zsh ]; then
  source $DOTFILES/zsh/extra.zsh
fi

# Plugins
source $DOTFILES/zsh/plugins/fzf.plugin.zsh
source $DOTFILES/zsh/plugins/git-trim/git-trim.plugin.zsh
source $DOTFILES/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $DOTFILES/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
source $DOTFILES/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"
eval "$(atuin init zsh --disable-up-arrow)"
eval "$(direnv hook zsh)"

# Has to be sourced *after* atuin
source $DOTFILES/zsh/key-bindings.zsh

# Include the zsh-completions plugin directory in the $fpath
fpath=($DOTFILES/zsh/plugins/zsh-completions/src $fpath)

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path --no-rehash)"
fi
