-- Navigate between nvim and tmux panes the same as with nvim splits
-- https://github.com/christoomey/vim-tmux-navigator
-- vim.keymap.set('n', '<C-m>', ':TmuxNavigateLeft<cr>')
-- vim.keymap.set('n', '<C-n>', ':TmuxNavigateDown<cr>')
-- vim.keymap.set('n', '<C-e>', ':TmuxNavigateUp<cr>')
-- vim.keymap.set('n', '<C-i>', ':TmuxNavigateRight<cr>')
